//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Livraria.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve requested author..
        /// </summary>
        public static string AuthorNotFound {
            get {
                return ResourceManager.GetString("AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book is not found..
        /// </summary>
        public static string BookNotFound {
            get {
                return ResourceManager.GetString("BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve requested category..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book with this ISBN already exists..
        /// </summary>
        public static string DuplicatedIsbn {
            get {
                return ResourceManager.GetString("DuplicatedIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given name already exists..
        /// </summary>
        public static string DuplicatedName {
            get {
                return ResourceManager.GetString("DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a category for the book..
        /// </summary>
        public static string InformCategory {
            get {
                return ResourceManager.GetString("InformCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a publisher for the book..
        /// </summary>
        public static string InformPublisher {
            get {
                return ResourceManager.GetString("InformPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the quantity of the book in stock..
        /// </summary>
        public static string InformStorageQty {
            get {
                return ResourceManager.GetString("InformStorageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must contain 3 to 200 characters..
        /// </summary>
        public static string InvalidBookTitle {
            get {
                return ResourceManager.GetString("InvalidBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the date of the book..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ISBN must contain 10 to 12 characters..
        /// </summary>
        public static string InvalidIsbn {
            get {
                return ResourceManager.GetString("InvalidIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must contain 3 to 150 characters..
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve requested publisher..
        /// </summary>
        public static string PublisherNotFound {
            get {
                return ResourceManager.GetString("PublisherNotFound", resourceCulture);
            }
        }
    }
}
